name: Build

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        cpu_arch: [armv7, aarch64, mips, amd64]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Build aMule
        run: |
          docker build -f Dockerfile -t builder .
          docker run --user $(id -u):$(id -g) --rm -t -v $PWD:/build builder sh -c "cd /build && ./scripts/gcc-musl.sh -arch=${{ matrix.cpu_arch }} && ./scripts/build.sh ${{ matrix.cpu_arch }}"

      - name: Upload build artifacts
        # if: always()
        uses: actions/upload-artifact@v3
        with:
          name: amule-linux-musl
          path: amule*.tar.xz
