name: Build

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpu_arch: [armv7, aarch64, mips, amd64]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            g++ autoconf automake make patch bison flex libtool git wget gettext texinfo p7zip-full pkg-config autopoint
          wget https://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz
          tar xf autoconf-2.69.tar.xz
          cd autoconf-2.69
          ./configure --prefix=/usr/local/autoconf
          make && sudo make install

      - name: Build musl GCC
        run: ./scripts/gcc-musl.sh -arch=${{ matrix.cpu_arch }}
          
      - name: Build aMule
        run: |
          export PATH=/usr/local/autoconf/bin:$PATH
          ./scripts/build.sh ${{ matrix.cpu_arch }}
